---
output:
  pdf_document: default
  html_document: default
  word_document: default
---
## \hfil OTHER ARCHAEOLOGICAL APPLICATIONS\hfil

### Chronological modelling
The reliable construction of chronologies is an integral part of all archaeological research. Consequently, an abundance of research has been conducted to create robust chronologies and thus, assist archaeologists in interpreting past events. Early work laid the foundation for the use of Bayesian methods in chronological modelling to improve precision [@naylor_archaeological_1988; @buck_combining_1991; @buck_calibration_1992]. The advent and continued improvement of user-friendly modelling software, including BCal [@buck_bcal_1999] and OxCal [@bronk_ramsey_analysis_1994; @bronk_ramsey_methods_2017], has enabled many archaeologists to employ Bayesian chronological modelling in their research. In fact, the construction of chronologies has been described as the one archaeological application of Bayesian methods that is now routine [@buck_being_2015].

There has been a documented increase in the use of Bayesian chronological modelling over the last decade [@bayliss_quality_2015; @hamilton_myths_2018], as numerous studies have re-examined radiocarbon dates to refine regional chronologies. Although these methods were initially used by archaeologists in the United Kingdom [@hamilton_myths_2018], Bayesian chronological studies have now been conducted in nearly every region of archaeological interest, including:

i. Central America [@inomata_high-precision_2017; @mendelsohn_chronology_2018; @tsukamoto_building_2020]; 
ii. South America [@marsh_dating_2017; @wynveldt_late_2017],
iii. Europe [@arvaniti_tracing_2018; @jimenez_cultural_2018; @krajcarz_towards_2018; @manning_new_2018; @ricci_chronological_2018; @paulsson_radiocarbon_2019],
iv. Asia [@long_bayesian_2017; @ricci_chronological_2018; @birch-chapman_bayesian_2019; @yang_refined_2019],
v. Africa [@kramer_sibling_2016; @brandt_new_2017; @sadr_new_2017; @loftus_archaeological_2019], and 
vi. Oceania [@brockwell_new_2017; @kirch_new_2017; @urwin_chronology_2018; @david_dating_2019].
 
Indeed, even those archaeologists who simply report individual, calibrated radiocarbon dates are now reliant on Bayesian methods since the most recent estimates of the radiocarbon calibration curves (IntCal20, SHCal20, and Marine20) are grounded in Bayesian inference. They were constructed using a Bayesian spline approach to combine data from tree rings, floating tree-ring chronologies, lacustrine and marine sediments, speleothems, and corals [@reimer_intcal20_2020].

Archaeologists have applied Bayesian methods to other methods of absolute dating. For example, recent studies have constructed chronological models using optically-stimulated luminescence (OSL) dates [@clarkson_human_2017; @combes_bayesian_2017; @veth_early_2017; @jimenez_cultural_2018; @demuro_corrigendum_2019; @heydari_bayesian_2020], and dendrochronology [@millard_bayesian_2002; @hassan_simple_2019; @lorentzen_shipbuilding_2020].
 
Perhaps most significantly, Bayesian chronological modelling enables archaeologists to include numerous sources of archaeological dates in a single interpretive framework, including those drawn from relative dating and absolute dating, to create chronologies of hard-to-date contexts. By combining relative dating and absolute dating methods with Bayesian modelling, archaeologists can produce more precise and accurate dates [@cowgill_we_2015]. For example, @croix_dating_2019 combined artifact chronologies, coin dates, and radiocarbon dating in a Bayesian model to date earthworks in Denmark. Prior to this research, dating these structures was difficult due to the limited survival of dateable artifacts and the reuse of building materials in antiquity. By constructing a Bayesian chronological model using coin age and radiocarbon dates, researchers improved the dating precision of the earthworks. Furthermore, @dinapoli_model-based_2020 used a Bayesian modelling approach to combine radiocarbon dates, stratigraphy, and ethnohistoric accounts to examine the collapse and resilience of populations on Rapa Nui. Other examples of studies include those combining absolute dating methods [e.g., @anyon_re-evaluating_2017; @fitzsimmons_chronological_2017; @smith_puntutjarpa_2017] and those drawing on relative and absolute dating methods [e.g., @guerin_chronology_2017; @douka_age_2019].
 
Other studies have used Bayesian modelling to clarify the complex relationship between humans and the environment. For example, Banks and colleagues (2019) utilized Bayesian hierarchical modelling to determine the date for cultures from Upper Palaeolithic France. These dates were then compared to palaeoecological records to determine the palaeoclimatic variability during each period. Similarly, @kearney_vegetation_2019 used Bayesian methods to combine archaeological and palaeoecological chronologies in a study examining the connection between vegetation changes and human activity near a megalithic tomb dating to the Neolithic in Ireland. Using this method, he was able to determine if significant palynological events occurred before, after or during the construction and use of the tomb. Ultimately, he determined that the clearing of the woodland occurred prior to the construction of the megalith. 
 
### Artifact analysis

Bayesian inference has been applied in numerous ways to study a broad array of artifacts, including ceramics, bone and stone tools. Early applications examined the provenance of artifacts and ceramic seriation [e.g., @buck_computational_1990; @buck_bayesian_1996;  @halekoh_bayesian_1999; @robertson_spatial_1999]. Continued research examining ceramics has utilized Bayesian modelling of radiocarbon dates to determine the chronologies of ceramic artifacts by combining absolute dating and studies of ceramic typologies [e.g., @naylor_archaeological_1988]. Similar methods have been used to examine ceramic traditions in Europe [@krol_chronology_2020], Bolivia [@marsh_temporal_2019], Guatemala [@arroyo_refining_2020], and Papua New Guinea [@skelly_changing_2018]. The combination of chronological modelling and ceramic data has been used to examine the dispersal and spread of ceramic cultures [e.g., @mehault_applying_2017; @binder_modelling_2018]. 
 
Recently, the application of Bayesian modelling to ceramic analysis has extended beyond seriation. For example, @fernandes_reconstruction_2018 used a Bayesian approach to identify the types of food that created residues in prehistoric European pottery. By analysing carbon isotope measurements and comparing them with measurements from known sources, the authors determined which foods had contributed to the residues and thus how the pots had been used. Since pots are reused to prepare multiple types of foods, results can be ambiguous when identifying the foods contributing to residues. The use of Bayesian methods addressed this ambiguity by estimating the contribution of various food types to the residues. 
 
Furthermore, Bayesian methods are becoming integral in the study of stone and bone tools. Researchers have used Bayesian methods to test hypotheses about stone tool assemblages [e.g., @marwick_early_2016] and develop techniques for studying stone tools. These techniques allow researchers to assign probabilities to the phenomenon being studied. For example, @murray_new_2020 developed a novel method combining 3D microscopic analyses of surface roughness and a Bayesian probability model to evaluate if Middle Stone Age silcrete tools from Pinnacle Point 13B (South Africa) had been heat treated. The model measured the probability that a tool has been heat treated,allowed for the continued updating from future heat treatment experiments, and performed with high accuracy. Similarly, other researchers combined a taphonomic analysis of the surface of unworked bone and bone tools with multivariate Bayesian modelling to quantify the taphonomic changes on the surfaces of the unworked and worked bones to accurately predict the original surface of the bone tools [@martisius_time_2018; @martisius_method_2020].
 
### Zooarchaeology

Researchers have used Bayesian statistics to study zooarchaeological trends. Pioneering work by @fisher_mastodont_1987 used Bayesian inference to determine whether scavenging or hunting led to the creation of butchery marks on proboscidean assemblages. Recent work has focused on studying seasonality and domestication. For example, @parkington_contemporaneity_2020 used a Bayesian approach to study the seasonal use of Later Stone Age archaeological sites in South Africa. By reanalysing their previous studies on the timing of death using a Bayesian framework, they were able to determine, with greater accuracy, when hunter-gatherers would have used the sites where seal remains were found. Additionally, scholars have used Bayesian methods to construct phylogenies examining the domestication of animals, including swamp buffalo [@wang_whole_2017] and pigs [@xiang_origin_2017]. Other research has examined the foods consumed by domesticated animals. @blanz_identifying_2020 used Bayesian modelling to examine the diets of modern sheep, specifically the amount of seaweed consumed, which can be used as a reference sample for identifying similar consumption patterns in archaeological contexts. 

Additionally, archaeologists have used Bayesian methods to study faunal assemblages and make inferences about their use. For example, @osborn_bayesian_2019 constructed a Bayesian network model using ethnographic, ethnohistoric, and archaeological data to determine whether Andean faunal assemblages indicated feasting, sacrifice, or daily refuse. The primary benefit of using a Bayesian approach in the study was the resulting replicable analysis that eliminates the subjectivity present in interpreting faunal assemblages. Rather, this method reports the probabilities of the faunal assemblage representing each type of behaviour. Furthermore, @baumann_role_2020 used Bayesian methods to estimate the abundance of foxes and hares in Palaeolithic Europe to determine how their abundance changed over time as they were hunted by humans for their meat, fur, and teeth. The use of Bayesian methods in this study allowed the researchers to overcome a small sample size while modelling animal abundance.
 
Bayesian techniques have been used to develop and re-examine the methods used in zooarchaeological research. Researchers have used Bayesian inference to develop a reliable and replicable probabilistic method to distinguish between sheep and goat bones in archaeological contexts [@wolfhagen_probabilistic_2017]. Since goats and sheep are very similar species that share many traits, it can be difficult to distinguish between them. This method provides the probability that a specimen is a goat given the identified traits. Furthermore, @wolfhagen_re-examining_2020 has re-examined the “logarithm size index” (LSI), a method for comparing the body sizes of animals between assemblages that is typically used in studies of animal domestication. He suggests adopting Bayesian multilevel LSI models to examine hypotheses about faunal assemblages.
 
### Bioarchaeology 

The use of Bayesian methods in bioarchaeological analyses was pioneered by Konigsberg and colleagues for studying age-at-death and stature estimation [e.g., @konigsberg_estimation_1992; @konigsberg_paleodemography_1994; @lucy_bayesian_1996; @konigsberg_stature_1998]. Recent research has continued to apply Bayesian statistics to the construction of biological profiles. For example, @anzellini_estimating_2019 proposed the use of Bayesian logistic regression to account for uncertainty in the sample when estimating the sex of individuals found in commingled contexts in the Andes. Although the frequentist and Bayesian approaches produced similar results, the authors demonstrated the validity of using Bayesian methods to account for uncertainty and to produce usable demographic profiles in bioarchaeological studies. Furthermore, @rosenstock_human_2019 used Bayesian additive mixed modelling to examine the global spatiotemporal trend in stature. This method enabled the researchers to account for spatiotemporally patchy data as well as fragmentary skeletal samples.
 
Further studies have utilized Bayesian mixing models to reconstruct prehistoric diets. Typically, these methods have used carbon and nitrogen stable isotope data to determine the types of foods people were eating. One popular method is called the Food Reconstruction Using Isotopic Transferred Signals (FRUITS) approach, which can account for multiple dietary sources and the uncertainty inherent in dietary inference. For example, @pezo-lanfranco_middle_2018 used Bayesian mixing models to quantify the proportion of three sources of food: plants, marine mammals, and terrestrial mammals. They determined that the people of the Atlantic Forest of South America consumed a large amount of carbohydrates, suggesting a unique diet compared to other populations in the area during the Middle Holocene. Using various Bayesian mixing models, other studies have examined prehistoric dietary trends in Europe [@bownes_using_2017; @sjogren_modelling_2017; @boethius_fish_2018;  @cubas_long-term_2019], South America [@gordon_dietary_2018], and Africa [@maurer_geochemical_2017]. Recent studies have used similar Bayesian modelling to study prehistoric weaning trends [@king_comparison_2017]. Specifically, using the FRUITS method, @de_angelis_dietary_2020 reconstructed the diet of those buried at the Quarto Cappello del Prete. From this reconstruction, they determined that Roman children were weaned around three years of age.

Other researchers have used mixed/multilevel/hierarchical modelling approaches. For example, @perri_dietary_2019 examined the canine diet as a proxy for human diets in archaeological contexts in Nicaragua. To infer the probability of the model’s parameters the authors used a Bayesian approach including MCMC to estimate the denominator of Bayes theorem. Hierarchical models in this context are flexible and scalable [@gelman_data_2006]. They can include individual and group level data in a model. This flexibility  provides improved inference on the parameters in question, resulting  in more accurate estimates of the model’s parameters [@katahira_how_2016]. 

### Spatial archaeology 

By combining prior knowledge regarding geographical data, archaeologists have been able to study spatial trends (see Chapter xx). For example, researchers have used Bayesian methods to examine the placement of archaeological sites on the landscape [@wright_analysis_2014] and predict the locations and settlement patterns of archaeological sites [@ortman_empirical_2007; @stewart_novel_2017]. Other research has incorporated Bayesian chronological modelling into spatial archaeological analyses. For example, @snitker_patch-based_2018 combined prehistoric land use maps generated by surveys, chronological data, and Bayesian methods to examine shifting occupation and land use patterns in Spain. The use of Bayesian methods in this study was critical as it allowed the researchers to make probabilistic inferences regarding the most likely occupation period at archaeological sites that may have been reused throughout history. Similarly, @wright_spatial_2020 used Bayesian chronological modelling of radiocarbon dates to construct a summed probability distribution estimating occupation events in the Baekje Kingdom of Korea during the Three Kingdoms Period (57 BCE to 688 CE). The researchers proceeded to use these data as part of a larger model examining the spatial distribution and dynamics of human activity areas over time. These methods allowed the researchers to make probabilistic statements about settlement patterns’ hypotheses at a time when occupation patterns were thought to be changing. 